UsersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: firstName
        AttributeType: S
    KeySchema:
      - AttributeName: userId
        KeyType: HASH
    BillingMode: PAY_PER_REQUEST
    TableName: ${self:custom.userTable}
    GlobalSecondaryIndexes: 
      - IndexName: firstName-index
        KeySchema: 
          - AttributeName: firstName
            KeyType: HASH
        Projection: 
          ProjectionType: ALL