org: manishrathod769
app: nodejs-adv
service: nodejs-adv

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline
  - serverless-middleware

frameworkVersion: '3'

custom:
  tableUser: users
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    # migration:
    #   dir: src/migration

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableUser}
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST  
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
